server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    db1:
      url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      #驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始连接数
      initial-size: 5
      #最小空闲数
      min-idle: 5
      #最大活动数
      max-active: 20
      #等待超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #验证数据库连接的查询语句,MYSQL是select 1
      validation-query: SELECT 1 FROM DUAL
      #空闲时测试，testOnBorrow和testOnReturn在生产环境一般是不开启的，主要是性能考虑。失效连接主要通过testWhileIdle保证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个链接上的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters,去掉后监控界面sql无法统计，‘wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall
      #通过connectproperties属性来打开mergesql功能：慢sql记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource
      useGlobalDataSourceStat: true
    db2:
      url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      #驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始连接数
      initial-size: 5
      #最小空闲数
      min-idle: 5
      #最大活动数
      max-active: 20
      #等待超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #验证数据库连接的查询语句,MYSQL是select 1
      validation-query: SELECT 1 FROM DUAL
      #空闲时测试，testOnBorrow和testOnReturn在生产环境一般是不开启的，主要是性能考虑。失效连接主要通过testWhileIdle保证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个链接上的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters,去掉后监控界面sql无法统计，‘wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall
      #通过connectproperties属性来打开mergesql功能：慢sql记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource
      useGlobalDataSourceStat: true