spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# 日志配置
logging:
  level:
    org.springframework.web: DEBUG
    com.ddl.web.system.generater.mapper: debug
    com.ddl.web.system.user.mapper: debug
  file:
    max-size: 50M

gen:
  author: drm
  packageName: com.ddl.web.system
  autoRemovePre: true
  tablePrefix: sys_

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

initialize:
  password: 123456

shiro:
  user:
    loginUrl: back/login