spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.1.151:9300

# 代码生成配置
gen:
  author: drm
  packageName: com.ddl.web.system
  autoRemovePre: true
  tablePrefix: sys_

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

initialize:
  password: 123456

shiro:
  user:
    loginUrl: back/login
logging:
  config: classpath:logback-spring.xml

swagger:
  title: Drm 接口文档
  description: Drm Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://www.baidu.com
  contact:
    name: Jxm
    url: https://www.baidu.com
    email: jinxmsir@163.com