spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false

# 日志配置
logging:
  level:
    com.ddl.web.system.generater.mapper: debug
  file:
    max-size: 50M

gen:
  author: drm
  packageName: com.ddl.web.system
  autoRemovePre: true
  tablePrefix: sys_

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql